# Generated by Django 5.2.6 on 2025-09-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('chapter', 'slug')},
        ),
        migrations.AddField(
            model_name='lesson',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('chapter', 'number'), ('chapter', 'slug')},
        ),
    ]
