# Generated by Django 5.2.6 on 2025-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_image_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_eur',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in EUR', max_digits=10),
        ),
    ]
